version: '3.9'

services:
  db:
    container_name: polls-db
    image: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    container_name: polls-backend
    build: backend
    entrypoint: sh entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/app/:cached
    env_file:
      - .env
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      - "db"

volumes:
  postgresdata:
  cached:
