version: '3.9'

services:
  db:
    container_name: polls-db
    image: postgres
    #volumes:
    #  - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=polls_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    container_name: polls-app
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    #restart: always